services:
  app:
    container_name: mini-reddit-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
        - MONGO_URI=${MONGO_URI}
        - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    container_name: mini-reddit-mongo
    image: mongo:8.2.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mini-reddit-mongo-data:/data/db
    restart: unless-stopped

volumes:
  mini-reddit-mongo-data:

    # pour l'ex√©cuter :
    # docker compose up -d
    # pour voir les logs
    # docker logs mini-reddit-api
